#config/local.yaml

env: "local"  # окружение - local, dev, или prod
storage_path: "./storage/storage.db"
app_secret: "test-secret"
http_server: # конфигурация нашего http-сервера
  address: "localhost:8500"
  timeout: 4s
  idle_timeout: 30s
  user: "my_user"
  password: "my_pass"