# config/prod.yaml

env: "prod"
storage_path: "./storage/storage.db"
cache:
  address: "localhost:6379"
  password: ""
  db: "0"
http_server:
  address: "0.0.0.0:8500" # 0.0.0.0 вместо localhost, чтобы работали внешние запросы
  timeout: 4s
  idle_timeout: 30s
  user: "my_user" # Указываем только user, но не password. О пароле поговорим ниже
  app_secret: "test-secret"